version: '3.8'
services:
  nginx:
    image: nginx-image
    container_name: nginx_server
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network

  tester:
    image: tester-image
    container_name: nginx_tester
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
