services:
  nginx:
    image: nginx-image
    container_name: nginx_server
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 8080 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 3

  tester:
    image: tester-image
    container_name: nginx_tester
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
