version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_server
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network

  tester:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: nginx_tester
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge