name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Nginx Image
        run: docker build -t nginx-image -f Dockerfile.nginx .

        run: docker build -t tester-image -f Dockerfile.python .

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 5

      - name: Run Tests
        run: docker wait nginx_tester
        id: test_step
        continue-on-error: true

      - name: Determine Test Result
        run: |
          EXIT_CODE=$(docker inspect nginx_tester --format='{{.State.ExitCode}}')
          if [ "$EXIT_CODE" -eq 0 ]; then
            echo "Tests succeeded."
            echo "test_result=succeeded" >> $GITHUB_OUTPUT
          else
            echo "Tests failed."
            echo "test_result=fail" >> $GITHUB_OUTPUT
          fi
        id: result_step

      - name: Create Artifact File
        run: echo "${{ steps.result_step.outputs.test_result }}" > ${{ steps.result_step.outputs.test_result }}

        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.result_step.outputs.test_result }}
          path: ${{ steps.result_step.outputs.test_result }}

      - name: Tear Down
        if: always()
        run: |
          docker-compose down -v --rmi all --remove-orphans
