name: CI Pipeline

on:
  push:
    branches: [ master, '**' ]
  pull_request:
    branches: [ master, '**' ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker Version
        run: docker version

      - name: Check Docker Compose Version
        run: docker compose version

      - name: Build Nginx Image
        run: docker build -t nginx-image -f Dockerfile.nginx .

      - name: Build Tester Image
        run: docker build -t tester-image -f Dockerfile.python .

      - name: Run Docker Compose
        run: docker compose up -d

      - name: Wait for services to start
        run: sleep 5

      - name: Run Tests
        id: test_step
        continue-on-error: true
        run: docker wait nginx_tester

      - name: Determine Test Result
        id: result_step
        run: |
          EXIT_CODE=$(docker inspect nginx_tester --format='{{.State.ExitCode}}')
          if [ "$EXIT_CODE" -eq 0 ]; then
            echo "Tests succeeded."
            echo "test_result=succeeded" >> $GITHUB_OUTPUT
          else
            echo "Tests failed."
            echo "test_result=fail" >> $GITHUB_OUTPUT
          fi

      - name: Create Artifact File
        run: echo "${{ steps.result_step.outputs.test_result }}" > result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.result_step.outputs.test_result }}
          path: result.txt

      - name: Tear Down
        if: always()
        run: docker compose down -v --rmi all --remove-orphans
